### ISSUE TITLE
API Keys don't work for Dalle 2

### ISSUE THREAD

**Issue by scottk2** [1998code/DALLE-2-App#13]
Hi there,

I tried this approach and package but it seems that teh API keys don't work for Dalle access (401). From what I've read, they don't support this at the moment. Did you get this working, and if so, does it still work for you?

Thanks!

**Comment by ezzcodeezzlife** [comment]
@scottk2 make sure you have a fresh bearer key. it runs out after some time ⏲️ (dont use GPT3 API key)

**Comment by realandygithub** [comment]
Hi, I have the same(?) issue. I had trouble getting the bearer key when I visit https://labs.openai.com/api/labs/tasks, because it prompted me for a username and password. As I only login with google oAuth, I don't have a username & password for openai. I also tried to put my api key in my password and leaving username blank, but no luck...

I tried to input my api key into the app directly, and it throws the error below.

Error: getaddrinfo EAI_AGAIN labs.openai.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:83:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'labs.openai.com'
}

**Comment by ezzcodeezzlife** [comment]
@realandygithub make sure you are invited through the waitlist... then getting the bearer key should work like described in the readme. do not use the GPT3 Api Key 🗝️

**Comment by 1998code** [comment]
Hi @scottk2  @realandygithub,

Please see the steps below for your reference.

1. Open https://labs.openai.com/ and Right Click to inspect. Go to network. You may need to refresh the page first.
![CleanShot 2022-07-16 at 00 22 23@2x](https://user-images.githubusercontent.com/54872601/184540063-596133d6-c259-44a5-bbc3-df471636e822.png)

2. Input something and click generate
<img width="640" alt="CleanShot 2022-07-16 at 00 21 26@2x" src="https://user-images.githubusercontent.com/54872601/184540072-7495c659-6269-4aae-a9c6-8425cb824277.png">

3. Find the Tasks, and scroll down to see your token.
![CleanShot 2022-07-16 at 00 24 16@2x](https://user-images.githubusercontent.com/54872601/184540087-0b78ebb8-014a-47f7-b178-eec9a01b89eb.png)

Let me know if it works for you.

**Comment by realandygithub** [comment]
It works! Thank you!

**Comment by xishoon** [comment]
The token expired after some time. How we can avoid this ? I Don't want to get token through inspect element again and again. Is there any solution ?

**Comment by 1998code** [comment]
@xishoon Please try the latest v2 instead.
